name: CI_on_Ubuntu-latest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: installing system dependencies
      run: sudo apt-get install -y build-essential pkg-config automake libncurses5-dev autotools-dev libparted-dev dmidecode
    - name: creating autoconf files
      run: ./init.sh
    - name: configure
      run: ./configure CFLAGS='-O0 -g -Wall -Wextra'
    - name: make
      run: make
